### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by lendormix** [FlYos/Prestashop-override-module#1]
Bonjour,
Merci pour le code :+1: 
J'ai slicé légèrement l'organisation pour pouvoir packager l'override de module pour le rendre lui aussi modulaire.

Voici les restructurations faites : ModuleOverride.php et Module.php dans un même fichier Module.php (déclaration des classes à la suite des autres) avec commentaire de la ligne

``` php
// require_once 'ModuleOverride.php';
```

Ainsi je peux insérer le fichier Module.php dans un module créé spécialement pour les overrides : 
/modules/monoverrider/override/classes/Module.php

Installer le module **monoverrider** ensuite mets à jour tout seul /cache/class_index.php.
Ca marche aussi à la désinstall.

Pour l'instant ça a l'air de bien fonctionner en 1.5.4.1 :)

**Comment by SebBareyre** [comment]
Peux-tu me copier le contenu de ce fichier override de la classe Module ? Merci.

**Comment by FlYos** [comment]
Bonjour,

Désolé pour la réponse très tardive, mais je n'ai reçu aucun alerte de la part de github. bref....

J'avais moi même fait un unique fichier lors de la création du projet, mais pour qu'il soit plus personnalisable, j'ai préféré le publié de façon splité.

Ainsi chaque est libre de l'utiliser à sa guise.
