### ISSUE TITLE
Ne fonctionne pas

### ISSUE THREAD

**Issue by te-deum** [FlYos/Prestashop-override-module#4]
Bonjour,

Je suis tombé sur ce module que je viens de tester sur Prestashop 1.6.0.8 et il semble que les surcharges ne fonctionnent pas sur le Front et le Back office de Prestashop.

J'ai essayé de mettre ces surcharges de la classe Module dans les dossier /override/module et dans /override/classes/module.

Suis-je passé à coté de quelque chose ou celà ne fonctionne-t-il pas avec Prestashop 1.6 ?
Merci de l'aide que vous saurez m'apporter.

**Comment by SebBareyre** [comment]
Bonsoir,
les surcharges sont à déposer dans le dossier /override/classes/module/
Une fois ces fichiers sur le serveur, pensez à vider le cache (Interface d'admin > Paramètres avancés > Performances clic sur le bouton "Vider le cache" en haut à droite. Ceci afin prendre en compte les modifications dans le class_index.php.

**Comment by FlYos** [comment]
Bonjour,
Je rajouterai à la réponse de SebBareyre de supprimer manuellement le fichier cache/class_index.php pour prendre en compte les surcharges

**Comment by te-deum** [comment]
Bonjour,

Désolé pour le délai de réponse mais je viens de faire la manipulation et tout fonctionne parfaitement.
Merci pour votre aide et pour cette ajout de fonction à Prestashop !

Il faudrait juste modifier le readme afin de donner le bon emplacement des fichiers qui doit être _/override/classes/module/_ au lieu de _/override/module/_. Il faudrait aussi préciser qu'il faut vider ce cache.

**Comment by FlYos** [comment]
Bonjour, je vais le modifier, car effectivement le path n'est pas le bon ;)
